name: lotti
description: A Smart Journal.
publish_to: 'none'
version: 0.8.72+1050

msix_config:
  display_name: Lotti
  publisher_display_name: Matthias Nehlsen
  publisher: CN=Matthias Nehlsen, O=Matthias Nehlsen, C=DE
  identity_name: com.matthiasnehlsen.lotti
  capabilities: internetClient, location, microphone, webcam
  languages: en-us, de-de, ro-ro
  install_certificate: false
  sign_msix: false
  #logo_path: C:\lotti\logo.png

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  adaptive_dialog: ^1.3.0
  arb_utils: ^0.2.0
  audio_video_progress_bar: ^0.10.0
  auto_route: ^4.0.1
  auto_size_text: ^3.0.0
  badges: ^2.0.2
  bloc: ^8.0.1
  bloc_test: ^9.0.1
  cached_network_image: ^3.2.0
  charts_flutter: ^0.12.0
  collection: ^1.16.0
  connectivity_plus: ^2.1.0
  crypto: ^3.0.1
  cryptography: ^2.0.2
  cupertino_icons: ^1.0.2
  dart_geohash: ^2.0.1
  delta_markdown: ^0.6.0
  device_info_plus: ^3.1.0
  drift: ^1.1.0
  easy_debounce: ^2.0.2+1
  encrypt: ^5.0.1
  enough_mail: ^2.0.0
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  exif: ^3.0.1

  flutter:
    sdk: flutter

  flutter_app_badger: ^1.3.0
  flutter_bloc: ^8.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.0.2
  flutter_fadein: ^2.0.0
  flutter_fgbg: ^0.2.0
  flutter_form_builder: ^7.2.1

  flutter_health_fit:
    git:
      url: https://github.com/matthiasn/flutter_health_fit.git
      ref: 37afbc9

  flutter_image_compress: ^1.1.0
  flutter_image_slideshow: ^0.1.2
  flutter_local_notifications: ^9.2.0

  flutter_localizations:
    sdk: flutter

  flutter_map: ^0.14.0
  flutter_native_timezone: ^2.0.0
  flutter_quill: ^5.0.3
  flutter_secure_storage: ^5.0.0
  flutter_sliding_tutorial: ^1.1.3+3
  flutter_sound: ^8.3.12
  flutter_svg: ^1.0.3
  flutter_typeahead: ^4.0.0
  form_builder_validators: ^8.1.1
  freezed_annotation: ^2.0.3
  geoclue: ^0.1.0
  get_it: ^7.2.0
  getwidget: ^2.0.4
  glass: ^1.0.1+1
  google_fonts: 2.2.0

  # health: ^3.4.3
  health:
    git:
      url: https://github.com/matthiasn/flutter-plugins
      path: packages/health
      ref: bfa66d6

  hexcolor: ^2.0.6
  hotkey_manager: ^0.1.6
  intl: ^0.17.0
  json_annotation: ^4.4.0
  just_audio: ^0.9.12
  keyboard_dismisser: ^2.0.0
  latlong2: ^0.8.1
  location: ^4.3.0
  lottie: ^1.2.2
  material_design_icons_flutter: ^5.0.6595
  material_floating_search_bar: ^0.3.6
  multi_select_flutter: ^4.0.0
  mutex: ^3.0.0
  package_info_plus: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.8
  permission_handler: ^10.0.0
  photo_view: ^0.14.0

#  qr_code_scanner: ^0.7.0
  qr_code_scanner:
    git:
      url: https://github.com/xeinebiu/qr_code_scanner.git
      ref: fix_break_changes_platform

  qr_flutter: ^4.0.0

  radial_button:
    git:
      url: https://github.com/redinterface/radial_button
      ref: 8140fcf

  # research_package: ^0.6.7
  research_package:
    git: https://github.com/matthiasn/research.package.git

  share_plus: ^4.0.4
  sqflite: ^2.0.1
  sqlite3_flutter_libs: ^0.5.2
  syncfusion_flutter_calendar: ^20.1.47
  syncfusion_flutter_datepicker: ^20.1.47
  timezone: ^0.8.0
  tinycolor2: ^2.0.0
  tuple: ^2.0.0
  url_launcher: ^6.1.2
  uuid: ^3.0.4
  wechat_assets_picker: ^7.0.1
  window_manager: ^0.2.0
  yaml: ^3.1.0

dependency_overrides:
  collection: ^1.16.0
  connectivity_plus_windows: 1.2.0
  crypto: ^3.0.2
  flutter_quill: ^5.0.3
  rxdart: ^0.27.1
  very_good_analysis: ^3.0.1
  xml: ^5.3.1

dev_dependencies:
  archive: ^3.1.6
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.4
  dart_code_metrics: ^4.8.1
  drift_dev: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.1.3+1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3
  glados: ^1.1.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mocktail: ^0.3.0
  msix: ^3.5.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/logo_1024_android.png"

analyzer:
  plugins:
    - drift

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/sqlite/
    # from https://www.iconfinder.com/paomedia
    - assets/images/map/299087_marker_map_icon.png
    # from https://www.iconfinder.com/recepkutuk
    - assets/images/map/728975_location_map_marker_pin_place_icon.png
    - assets/images/tutorial/
    - assets/lottiefiles/

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-ExtraLight.ttf
        - asset: assets/fonts/Oswald-Light.ttf
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Medium.ttf
        - asset: assets/fonts/Oswald-SemiBold.ttf
        - asset: assets/fonts/Oswald-Bold.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Thin.ttf
        - asset: assets/fonts/Lato/Lato-Light.ttf
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
        - asset: assets/fonts/Lato/Lato-Black.ttf
        - asset: assets/fonts/Lato/Lato-ThinItalic.ttf
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato/Lato-Italic.ttf
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
    - family: ShareTechMono
      fonts:
        - asset: assets/fonts/ShareTechMono-Regular.ttf

flutter_native_splash:
  color: "#283c5c"
