name: Flutter TestFlight

on:
  push:
    branches:
      - 'testflight-release'

jobs:
  test:
    name: Flutter TestFlight release on iOS and macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.0'
          channel: 'stable'
      - name: Fastlane match iOS
        working-directory: lotti/ios
        run: >
          fastlane match --generate_apple_certs false
          --git_basic_authorization $MATCH_GIT_BASIC_AUTHORIZATION
          --readonly true
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      - name: Fastlane match macOS
        working-directory: lotti/macos
        run: >
          fastlane match --platform macos
          --generate_apple_certs false
          --git_basic_authorization $MATCH_GIT_BASIC_AUTHORIZATION
          --readonly true
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
#      - name: Run Flutter build and publish
#        working-directory: ./lotti
#        run: make all
