name: Flutter Windows

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Flutter Build on Windows
    runs-on: windows-2019
    steps:
      - name: core.symlinks
        run: |
          git config --global core.symlinks true
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.2'
          channel: 'stable'
      - name: Flutter Doctor
        run: make doctor
      - name: Flutter get dependencies
        run: flutter pub get
      - name: Flutter build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Flutter test
        run: flutter test
      - name: Flutter build
        run: flutter build windows
      - name: Flutter create MSIX
        run: flutter pub run msix:create
