name: lotti
description: A Smart Journal.
publish_to: 'none'
version: 0.7.10+731

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_health_fit:
    git:
      url: https://github.com/metaflowltd/flutter_health_fit.git
      ref: 30102b6

  # research_package: ^0.6.7
  research_package:
    git: https://github.com/matthiasn/research.package.git

  enough_mail:
    git:
      url: https://github.com/Enough-Software/enough_mail
      ref: 80c8900

  radial_button:
    git:
      url: https://github.com/matthiasn/radial_button
      ref: 3137f03

  # enough_mail: ^1.3.6
  adaptive_dialog: ^1.3.0
  arb_utils: ^0.2.0
  audio_video_progress_bar: ^0.10.0
  auto_route: ^3.2.4
  badges: ^2.0.2
  bloc: ^8.0.1
  bloc_test: ^9.0.1
  cached_network_image: ^3.2.0
  charts_flutter: ^0.12.0
  connectivity_plus: ^2.1.0
  crypto: ^3.0.1
  cryptography: ^2.0.2
  cupertino_icons: ^1.0.2
  dart_geohash: ^2.0.1
  delta_markdown: ^0.6.0
  device_info_plus: ^3.1.0
  drift: ^1.1.0
  easy_debounce: ^2.0.2+1
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  exif: ^3.0.1
  flutter_app_badger: ^1.3.0
  flutter_bloc: ^8.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.0.2
  flutter_fgbg: ^0.2.0
  flutter_form_builder: ^7.0.0
  flutter_image_compress: ^1.1.0
  flutter_image_slideshow: ^0.1.2
  flutter_local_notifications: ^9.2.0
  flutter_map: ^0.14.0
  flutter_native_timezone: ^2.0.0
  flutter_quill: ^4.0.1
  flutter_secure_storage: ^5.0.0
  flutter_sliding_tutorial: ^1.1.3+3
  flutter_sound: ^8.3.12
  flutter_svg: ^1.0.3
  flutter_typeahead: ^3.2.4
  form_builder_validators: ^7.2.0
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  getwidget: ^2.0.4
  glass: ^1.0.1+1
  go_router: ^3.0.1
  google_fonts: 2.2.0
  health: ^3.4.3
  hexcolor: ^2.0.6
  hotkey_manager: ^0.1.6
  intl: ^0.17.0
  json_annotation: ^4.4.0
  just_audio: ^0.9.12
  keyboard_dismisser: ^2.0.0
  latlong2: ^0.8.1
  location: ^4.3.0
  lottie: ^1.2.2
  material_design_icons_flutter: ^5.0.6595
  material_floating_search_bar: ^0.3.6
  multi_select_flutter: ^4.0.0
  mutex: ^3.0.0
  package_info_plus: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.8
  permission_handler: ^9.2.0
  photo_view: ^0.13.0
  qr_code_scanner: ^0.7.0
  qr_flutter: ^4.0.0
  sqflite: ^2.0.1
  sqlite3_flutter_libs: ^0.5.2
  syncfusion_flutter_calendar: ^20.1.47
  syncfusion_flutter_datepicker: ^20.1.47
  timezone: ^0.8.0
  tinycolor2: ^2.0.0
  uuid: ^3.0.4
  wechat_assets_picker: ^7.0.1
  window_manager: ^0.2.0
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  archive: ^3.1.6
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.4
  dart_code_metrics: ^4.8.1
  drift_dev: ^1.1.0
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.1.3+1
  freezed: ^1.1.0
  glados: ^1.1.1
  json_serializable: ^6.0.0
  mocktail: ^0.3.0

analyzer:
  plugins:
    - drift

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/sqlite/
    # from https://www.iconfinder.com/paomedia
    - assets/images/map/299087_marker_map_icon.png
    # from https://www.iconfinder.com/recepkutuk
    - assets/images/map/728975_location_map_marker_pin_place_icon.png
    - assets/images/tutorial/
    - assets/lottiefiles/

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-ExtraLight.ttf
        - asset: assets/fonts/Oswald-Light.ttf
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Medium.ttf
        - asset: assets/fonts/Oswald-SemiBold.ttf
        - asset: assets/fonts/Oswald-Bold.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Thin.ttf
        - asset: assets/fonts/Lato/Lato-Light.ttf
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
        - asset: assets/fonts/Lato/Lato-Black.ttf
        - asset: assets/fonts/Lato/Lato-ThinItalic.ttf
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato/Lato-Italic.ttf
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
    - family: ShareTechMono
      fonts:
        - asset: assets/fonts/ShareTechMono-Regular.ttf

flutter_native_splash:
  color: "#283c5c"
